gitlab:
  global:
    edition: ce
  upgradeCheck:
    enabled: false
  
  hosts:
    domain: 192.168.1.233.nip.io
    externalIP: 192.168.1.233
  
  certmanager-issuer:
    email: umaa@zelarsoft.com
    install: false
  
  prometheus:
    server:
      persistentVolume:
        enabled: true
        storageClass: local-path
        accessMode:
          - ReadWriteOnce
        size: 4Gi
  
  redis:
    master:
      persistence:
        enable: true
        storageClass: local-path
        size: 4Gi
        accessMode:
          - ReadWriteMany
  
  postgresql:
    primary:
      persistence:
        enabled: true
        storageClass: local-path
        size: 4Gi
        accessMode:
          - ReadWriteMany
  
  gitlab:
    gitaly:
      persistence:
        enabled: true
        storageClass: local-path
        accessMode: ReadWriteOnce
        size: 10Gi
        matchLabels: {}
        matchExpressions: []
        subPath: "data"
        annotations: {}
  
  minio:
    persistence:
      enable: true
      storageClass: local-path
      size: 5Gi
      accessMode: ReadWriteOnce
